### PR TITLE
Test new LLMs (Llama2, CodeLlama, etc.)? 

### PR DESCRIPTION
**Pull request by ghost**
Hi @rminchev1 ,

if you're trying to test other LLMs (codellama, wizardcoder, etc.) with GPT-Engineer, we just open-sourced a 1-click proxy to translate openai calls to huggingface, anthropic, togetherai, etc. api calls.

**code**
```
$ pip install litellm

$ litellm --model huggingface/bigcode/starcoder

#INFO:     Uvicorn running on http://0.0.0.0:8000
```

Docs: https://docs.litellm.ai/docs/proxy_server

I'd love to know if this solves any problem for you

### CODE REVIEW

**Comment by rminchev1** [comment]
Thanks @krrishdholakia.  Will consider it.

**Comment by ghost** [comment]
Hey @rminchev1 is calling non-openai models a problem you currently face? 

Any feedback here would be great

**Comment by rminchev1** [comment]
@krrishdholakia not at the moment, but for sure it's a something I anticipate to have an easy way to leverage a multi-LLMs interface

**Comment by ghost** [comment]
@rminchev1 interesting - is there anything you feel [litellm](https://github.com/BerriAI/litellm) is missing to be helpful here?

**Comment by rminchev1** [comment]
@krrishdholakia, I'll have a  look at it shortly. On the first pass, it looks promising and is a time saver for sure

**Comment by ghost** [comment]
@rminchev1 thanks! are you currently exploring different LLMs?

**Pull request closed without merging**
